### ISSUE TITLE
KeeTrayTOTP fails to work on gitlab.com

### ISSUE THREAD

**Issue by xeropresence** [smorks/keepassnatmsg#59] opened 2020-07-16 05:50 UTC
KeeTrayTOTP 0.107.7453.5256
KeePassNatMsg 2.0.10.0
KeePass 2.45
KeePassXC-Browser Version: 1.6.6

Filling in the username and password works fine, prompt appears to fill in the field with the OTP, but nothing happens. OTP works fine on other websites such as protonmail.com. I first assumed with was a KeePassXC-Browser issue but after opening an issue there, they closed it suggesting it was a keepassnatmsg issue. Testing the same database in keepassxc the otp gets filled in correctly.

**Comment by gab** [comment] 2020-08-18 18:43
Slightly different issue, with an even worse failure on https://login.microsoftonline.com/common/oauth2/authorize
There is no TOTP prompt at all, which wouldn't be that big of a deal if right-clicking the field and filling the TOTP through the menu option worked, but it doesn't.

- The password is filled correctly by KeePassXC-Browser for the same entry
- The entry has a properly configured TOTP using KeeTrayTOTP
- When opening the same DB with KeepassXC it recognizes that the TOTP is configured.

Since I can't even tell it to fill the TOTP manually I'm assuming that the issue is on the KeePassNatMsg side (great software otherwise, thank you).

KeeTrayTOTP 0.107.7523.18689
KeePassNatMsg 2.0.10.0
KeePass 2.45
KeePassXC-Browser version : 1.6.6

**Comment by gab** [comment] 2020-09-15 01:16
Since 2.0.11 the TOTP fills correctly for me on https://login.microsoftonline.com/ . Thanks for the fix!

**Comment by smorks** [comment] 2021-08-04 20:29
hopefully all totp issues should be fixed. closing this issue.

**Closed by smorks** 2021-08-04 20:29 UTC
Labels: bug
