### ISSUE TITLE
Extension fails to connect to database after first successful connection

### ISSUE THREAD

**Issue by pcoombe** [smorks/keepassnatmsg#19] opened 2018-10-15 23:29 UTC
**Expected Behavior**
The extension connects to an unlocked database, and continues to do so even after the browser restarts.

**Current Behavior**
The extension behaves as expected immediately following successful installation from the chrome extensions store, but then breaks once the browser is closed. Upon a restart of the browser, the extension will be stuck saying that it has not been configured, even though it has been successfully configured already.

**Steps to Reproduce (for bugs)**
keepassxc-browser successfully installed from chrome extensions
Extension makes pop-up window requesting access to the database
Unique identifier given and access granted to extension
Tried logging into a website, extension works.
Closed Chrome.
Restarted Chrome.
Opened extension menu.
Dialog with error message saying that it is not configured, thinks it needs to connect again.

**Workaround**
Create new database connection
Press Cancel
Database is now connected, but extension doesn't report database connection name.

**Software Versions**
Windows 10
Chrome 69
keepassxc-browser 1.30
keepass 2.40
keepassnatmsg 2.0.1

[https://github.com/keepassxreboot/keepassxc-browser/issues/277](keepassxc-browser related issue)

**Comment by smorks** [comment] 2018-10-17 17:56
i've seen this happen before once or twice. i will try and reproduce it again and see if i can narrow down what exactly the problem is.

**Comment by smorks** [comment] 2018-10-18 16:14
i managed to reproduce the issue using a new profile in Chrome 70 on Windows 7. it appears to be a problem with the keepassxc-browser extension, but i'll do some more investigating to try and figure out why that's happening.

**Comment by smorks** [comment] 2018-10-18 17:36
i believe i found the commit which causes the issue.

keepassxreboot/keepassxc-browser@6e3f1de5fb791f60c7f7619d9843b6d2276d77d0

they changed how associating works slightly, so i should be able to have a fix for this in the next few days. thanks for the report!

**Closed** 2018-10-18 18:36 UTC
Labels: bug

**Comment by pcoombe** [comment] 2018-10-18 21:49
yep all working great, thanks!
