### ISSUE TITLE
KeePassXC-Browser won't stay connected

### ISSUE THREAD

**Issue by HarHarLinks** [smorks/keepassnatmsg#91] opened 2022-02-12 13:55 UTC
For a couple weeks now, whenever I try to use the browser extension to fill my passwords, it isn't connected. I click reconnect, then it goes into a state as if it never has been connected. Then I create a new connection and it works.
The next day, I have to repeat these steps.

Keepass 1.50 (220209)
KeePassXC-Browser - 1.7.11
Operating system: Linux x86_64
Browser: Chrome/Chromium 98.0.4758.88

**Comment by smorks** [comment] 2022-02-16 04:12
I thought it should at least mark the database as having changes, so when you close it should prompt to save changes. I will test and see what if I can reproduce.

**Comment by HarHarLinks** [comment] 2022-02-16 13:05
I had my keepass set to autosave when locking and autolock after timeout, yet it never got saved :/

**Comment by smorks** [comment] 2022-02-16 15:23
i confirmed the issue. will look into it more when i have some free time.

**Comment by smorks** [comment] 2022-02-16 15:55
duplicate of #85, closing this issue.

**Closed by smorks** 2022-02-16 15:55 UTC
Labels: bug
