### ISSUE TITLE
Proxy download error

### ISSUE THREAD

**Issue by allesmeins89** [smorks/keepassnatmsg#34] opened 2019-05-05 12:08 UTC
![Selection_001](https://user-images.githubusercontent.com/16083990/57193743-ec064480-6f3e-11e9-823c-87772cfc2ecd.png)

I get this error from screenshot on 2 clients than I install the Native Messaging Host.

System:
- Linux Mint 19 Cinnamon
- KeePass 2.41 and 2.42.1
- KeePassNatMsg 2.0.5
- Mono: [mono_pkgs.txt](https://github.com/smorks/keepassnatmsg/files/3145502/mono_pkgs.txt)

Steps to reproduce:
- download and extract KeePassNatMsg 2.0.5
- move into plugins directory
- start KeePass
- install Native Messaging Host

**Comment by smorks** [comment] 2019-05-06 19:05
looks like a dupe of #11 .

try the following command:

```
sudo cert-sync /etc/pki/tls/certs/ca-bundle.crt
```

**Comment by allesmeins89** [comment] 2019-05-13 11:34
```
sudo cert-sync /etc/pki/tls/certs/ca-bundle.crt  
Linux Cert Store Sync - version 4.6.2.0
Synchronize local certs with certs from local Linux trust store.
Copyright 2002, 2003 Motus Technologies. Copyright 2004-2008 Novell. BSD licensed.

I already trust 133, your new list has 133
Import process completed.
```

Error not fixed. I still have the problem.

**Comment by smorks** [comment] 2019-05-13 19:20
try the command listed here: https://www.mono-project.com/docs/faq/security/

```bash
csharp -e 'new System.Net.WebClient ().DownloadString ("https://www.nuget.org")'
```

and see if that gives you an error?

You can also download the file manually: https://github.com/smorks/keepassnatmsg-proxy/releases

And put the `keepassnatmsg-proxy.exe` file in the `~/.keepassnatmsg` directory, and then try to install the Native Messaging Host again?

**Closed** 2019-09-12 02:49 UTC
